
export enum AbstractDomainEnum {
  POKEMON = 'POKEMON',
  REGION = 'REGION',
  POKEDEX = 'POKEDEX',
  POKEMON_SPECIES = 'POKEMON_SPECIES',
  ITEM = 'ITEM',
  ITEM_CATEGORY = 'ITEM_CATEGORY',
  BERRY = 'BERRY',
}
